name: frappe_mobile_custom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.0
  connectivity: ^3.0.3
  cached_network_image: ^3.0.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.1.0
  flutter_typeahead: ^3.1.0
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  intl: ^0.17.0
  get: 4.6.5
  get_storage: ^2.1.1
  flutter_svg: ^0.22.0
  json_table: ^2.0.1
  timeago: ^3.0.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
